# Generated by Django 3.0.8 on 2020-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsmodel',
            name='creation_date',
            field=models.CharField(max_length=20),
        ),
    ]
